import type { Metadata } from "next";
import { roboto } from "./fonts";
import Theme from "@/app/components/Theme";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-neutral-200`}>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
